name: .NET Core

on:
  push:
    branches: [ "deploy" ]
  pull_request:
    branches: [ "deploy" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 6.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build library
      run: dotnet build --no-restore
    - name: Publish nuget
      uses: brandedoutcast/publish-nuget@v2.5.5
      with: 
        PROJECT_FILE_PATH: project/rgbxmastree.csproj
        NUGET_KEY: ${{secrets.NUGET_API_KEY}}
