name: .NET Core

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.100
    - name: Install dependencies
      run: dotnet restore
    - name: Build library
      run: dotnet build --configuration Release --no-restore
    - name: Publish nuget
      uses: brandedoutcast/publish-nuget@v2.5.2
      with: 
        PROJECT_FILE_PATH: project/rgbxmastree.csproj
        NUGET_KEY: ${{secrets.NUGET_API_KEY}}
